default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    adapter: postgresql
    database: MyAccount_development
  users:
    adapter: postgresql
    database: DataLionNav_development
    migrations_paths: db/users_migrate
  moviemakers:
    adapter: postgresql
    database: MovieMakers_development
    migrations_paths: db/moviemakers
  lionsocail:
    adapter: postgresql
    database: LionSocial_development
    migrations_paths: db/lionsocail
  railsforums:
    adapter: postgresql
    database: Ror_development
    migrations_paths: db/railsforums
production:
  primary:
    adapter: postgresql
    url: <%= ENV['HEROKU_POSTGRESQL_GOLD_URL'] %>
  users:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/users_migrate
  moviemakers:
    adapter: postgresql
    url: <%= Rails.application.credentials.dig(:database, :moviemakers) %>
    migrations_paths: db/moviemakers
  lionsocail:
    adapter: postgresql
    url: <%= Rails.application.credentials.dig(:database, :lionsocail) %>
    migrations_paths: db/lionsocail
  railsforums:
    adapter: postgresql
    url: <%= Rails.application.credentials.dig(:database, :railsforums) %>
    migrations_paths: db/railsforums
